apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ijmxuw07h-python 
  janus-idp.io/tekton: ijmxuw07h-python
  backstage.io/kubernetes-id: ijmxuw07h-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ijmxuw07h-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml